(<any>window).d3 = require('d3');
(<any>window).Vizabi = require('vizabi');
require('vizabi-barrankchart');
require('vizabi-mountainchart');
require('vizabi-bubblechart');
require('vizabi-linechart');
require('vizabi-bubblemap');
require('vizabi-popbyage');
require('vizabi-extapimap');
require('vizabi-barchart-ds');
